language: python
python: 2.7

addons:
  apt:
    packages:
     - npm
     - node
install:
  - ./install.sh
script:
  - ./build.sh
  - ./tests/test-custom-check.sh
notifications:
  email: false
sudo: required
os:
  - linux